src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $UpdatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->CreatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title', null, [
                'label' => 'Titre de l\'article',
            ])
            ->add('Content', null, [
                'label' => 'Contenu de l\'article',
            ])
            ->add('Image', null, [
                'label' => 'URL de l\'image d\'illustration',
            ])
            ->add('Submit', SubmitType::class, [
                'label' => 'Envoyer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article/{id}", name="article_show", requirements={"id": "\d+"})
     */
    public function show(int $id, ArticleRepository $articleRepository, Request $request, EntityManagerInterface $manager): Response
    {
        $article = $articleRepository->find($id);

        // Creating the form to add a comment under an article
        $form = $this->createForm(CommentType::class);

        // Handling information received with the form
        $form->handleRequest($request);

        if ($this->getUser()) {
            if ($form->isSubmitted() && $form->isValid()) {
                $comment = $form->getData();
    
                //The author is the current user in session
                $author = $this->getUser();
    
                $comment->setAuthor($author);
                $comment->setArticle($article);
    
                $manager->persist($comment);
                $manager->flush();

                $this->addFlash('success', 'Votre commentaire a bien été enregistré.');
            }
        }


        return $this->render('article/show.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/article/add", name="article_add")
     */
    public function add(Request $request, EntityManagerInterface $manager): Response
    {
        // Creating the form to create a new article
        $form = $this->createForm(ArticleType::class);

        // Handling information received with the form
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();

            //The author is the current user in session
            $author = $this->getUser();

            $article->setAuthor($author);

            $manager->persist($article);
            $manager->flush();

            $this->addFlash('success', 'Votre article a bien été enregistré.');

            return $this->redirectToRoute('article_show', ['id' => $article->getId()]);
        }

        return $this->renderForm('article/form.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/article/update/{id}", name="article_update", requirements={"id": "\d+"})
     */
    public function update(Request $request, EntityManagerInterface $manager, Article $article)
    {
        $this->denyAccessUnlessGranted('EDIT', $article);

        // Creating the form to update the article
        $form = $this->createForm(ArticleType::class, $article);

        // Handling information received with the form
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->flush();

            $this->addFlash('success', 'Votre article a bien été mis à jour.');

            return $this->redirectToRoute('article_show', ['id' => $article->getId()]);
        }

        return $this->renderForm('article/form.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/article/delete/{id}", name="article_delete", requirements={"id": "\d+"})
     */
    public function delete(EntityManagerInterface $manager, Article $article)
    {
        $this->denyAccessUnlessGranted('DELETE', $article);
        
        $manager->remove($article);
        $manager->flush();

        $this->addFlash('success', 'Votre article a bien été supprimé.');

        return $this->redirectToRoute('home');
    }
}

templates/article/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{{ form(form) }}

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="card my-5">
        <div class="card-body">
            <h1 class="text-center">{{ article.title }}</h1>
            <p>écrit par {{ article.author.username }}</p>
            <img style="width: 80%;" class="d-block mx-auto my-4" src="{{ article.image }}" alt="...">
            <p>{{ article.content }}</p>
        </div>
    </div>

    {# Form to add a comment received from the controller #}
    {{ form_start(form) }}
        {# Error messages #}
        {{ form_errors(form) }}
        {{ form_row(form.content) }}
        {{ form_row(form.submit) }}
    {{ form_end(form) }}

    {% for comment in article.comments %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    <div class="card my-4">
                        <div class="card-header">Commentaire de {{ comment.author.username }}</div>
                        <div class="card-body">
                            <p class="card-text">{{ comment.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="card my-5">
        <div class="card-body">

        {% if( app.user == article.author) %}

        <a href="{{ path( 'article_update', {id:article.id} ) }}" class="btn btn-primary">Modifier cet article</a>
        <a href="{{ path( 'article_delete', {id:article.id} ) }}" class="btn btn-primary">Supprimer cet article</a>

        {% endif %}

            <h1 class="text-center">{{ article.title }}</h1>
            <p>écrit par {{ article.author.pseudonyme }}</p>
            <img style="width: 80%;" class="d-block mx-auto my-4" src="{{ article.image }}" alt="...">
            <p>{{ article.content }}</p>
        </div>
    </div>

    {% if app.user %}
        {# Form to add a comment received from the controller #}
        {{ form_start(form) }}
            {# Error messages #}
            {{ form_errors(form) }}
            {{ form_row(form.content) }}
            {{ form_row(form.submit) }}
        {{ form_end(form) }}
    {% else %}
        <p class="fs-3 text-center"><a href="{{ path ( 'app_login' ) }}">Connectez vous</a> pour pouvoir ajouter un commentaire.</p>
    {% endif %}

    {% for comment in article.comments %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    <div class="card my-4">
                        <div class="card-header d-flex justify-content-between">
                        <p>Commentaire de {{ comment.author.pseudonyme }}</p>

                        {% if(app.user == comment.author) or is_granted('ROLE_ADMIN') %}

                        <div>
                            <a href="{{ path( 'comment_update', {id:comment.id} ) }}" class="btn btn-success">Modifier</a>
                            <a href="{{ path( 'comment_delete', {id:comment.id} ) }}" class="btn btn-success">Supprimer</a>
                        </div>

                        {% endif %}

                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ comment.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}